### ISSUE TITLE
Issue with sessions and grist

### ISSUE THREAD

**Issue by MarioBG** [mraof/Minestuck#121]
Yesterday I was playing a 2-player game of Minestuck and my co-player signed out of Minecraft to do some stuff, so I reshuffled the connections and had me connecting to myself with the Sburb computers to deploy the Punch Designix (while already in the Medium). However, although I had a bit of every kind of grist, it didn't show up and I couldn't deploy it. What's worse, when she logged back in and we set the connections right again, her grist worked just fine, but mine didn't. When I set out to investigate the MinestuckData.dat I found that there were two session packages and four player packages (I will put the [screenshots of that here](https://drive.google.com/open?id=0B8-MZmg1OkeERzJ1N3puZVFyQTQ) when I get back to that computer). This can be very problematic, especially since all players can't be connected at the same time and many may want to do this. Thanks!

**Comment by kirderf1** [comment]
Found out that grist wasn't updated as it should when deploying the punch designix. But by the sound of it, there's more to it. I'll await the MinestuckData.dat stuff and a more detailed walkthrough for how I could repeat the issue.

**Comment by MarioBG** [comment]
I have now uploaded the MinestuckData.dat file to the Google Drive folder, hope you can figure it out soon :) good luck with it! The walkthrough is also included in the folder.

**Comment by kirderf1** [comment]
I think I've got an understanding on what happened, and the main problem is that your player uuids aren't consistent (usually caused by playing in offline mode)
When you logged back in, you got a new uuid, which made minestuck handle you as a new player, creating a new grist cache for you and handling you as a new player, who haven't entered yet, instead of the Sylph of Blood you entered as.
Do you think this could be the problem? Does it work if you turn off `uuidIdentification` in the server minestuck config, or turn on `online-mode` in the server properties (assuming it actually is off)?
