### ISSUE TITLE
Error on entering medium in 1.10.2

### ISSUE THREAD

**Issue by HardInk** [mraof/Minestuck#124]
https://pastebin.com/APvCZ6pN

**Comment by BenjaminKirksey** [comment]
Currently, Minestuck biomes are set up a little strangely in a way that doesn't lend itself well to referencing them with Forge. Forge itself doesn't _require_ that you register your biomes with it, but some Forge mods get a little pushy and demand certain information from every biome in the game. (In the case of Forestry, this information is temperature and humidity. This is the most common interaction to create this particular issue. We can't set up biomes to have that kind of information, because a Heat land and a Frost land are composed of the same biomes, but very different biome information. In your case, it was COFH core, but the same concept applies.) If the biome fails to give the information these mods demand, the mods will often crash.
The _best_ solution would be for these other mods to recognize that not all biomes will have the information they're looking for and create appropriate workarounds (you can't raise bees in the Medium, to follow the prior example), but the easiest way to fix the problem as we, the developers of Minestuck, see it, would be to actually fudge some kind of biome data to give to Forge.

**Comment by kirderf1** [comment]
The forge biome dictionary class is not looking the same as how it was back when this crash happened. It is likely that the game will not crash in the same way as shown in that crash log. If such a problem still exists with the latest version, please open a new issue with a new issue description.
