### ISSUE TITLE
Alchemy Tab, Rose's Walkthrough, Captchalogue Codes, and Frog Temples

### ISSUE THREAD

**Issue by Kellosian** [mraof/Minestuck#251]
The first one, the Alchemy Tab, would mainly be a nice QOL change. As I played I ended up with a chest full of nigh-identical carved cruxite dowels that AFAIK I couldn't get rid of since they were still required to alchemize items. In order to prevent this, I suggest implementing the Alchemy tab into the alchemiter which would allow players to re-alchemize items they've already made without digging through chests for cruxite dowels. (As an aside, server players were capable of using their client's alchemiters and really most of the alchemy process at the expense of their grist, although since I played single-player I don't know if this is a feature)

The second would be a nice form of in-game documentation: Rose's Walkthrough. Since MineStuck is naturally going to be a bit different from how it works in the comic, copy-pasting it verbatim probably isn't super helpful so an in-game guide written by the devs could be made available via players' PCs. It could be more of a getting started guide, perhaps with other forms of in-game documentation available as dungeon rewards or by completing side quests for consorts? Light players, for example, could be given extra information sources to help differentiate aspects in more subtle ways.

Third, implementing some system of captchalogue codes would help players share items without having to physically travel between lands. In order to prevent just having a list of codes off of a wiki they could be semi-randomized or only unlocked through players already having the item in question (no mashing keys at the Punch Designix, since programming in a measly few trillion items is _apparently_ beyond the devs :P).

Fourth, crafting the Sburb disks just kind of felt... wrong in a way I can't describe without resorting to "that's not how they did it in the comic". While being able to craft them outright is probably the best for expediting getting into the mod, perhaps a world setting would allow/disallow this with the only way to get the disks being plundering a Frog Temple with some way to duplicate them from there to account for having more/less players. Cartographer villagers could offer maps to Frog Temples or some kind of compass could be made.

And finally some rapid-fire suggestions that I would consider much lower on the wish list either because they're not important or I'm under the assumption they'll be implemented in some form later on.
1. Hardcore worlds work on Homestuck death rules, i.e. players can resurrect as their Dream Selves if another player is nearby and kisses them... somehow
2. Single-player Dead Sessions
3. QCraft has a feature that allows for players to hop between servers, perhaps some super-rare 4th Wall could allow this here?
4. The ability to play as a Troll with an Alternia world setting for the overworld
5. A config that disables the in-game chat and requires players to use Pesterchum (Also, implement Pesterchum!)
6. A config that disables the in-game inventory and requires players to use their Sylladex
7. Clothing that covers the player's skin but can be worn under armor
8. Rocket packs, I just want to go PCHOOOOO
9. A First Guardian somewhere on the MineCraft overworld
10. A config that enables the Reckoning to destroy the overworld if players don't enter the game within a certain time limit of getting the Sburb disks

**Comment by blahthebiste** [comment]
A lot of these are great,
I totally agree about alchemy, some way to store the punch cards/dowels would be nice. I get that in the comic they did it all manually, but they also did it all off-screen, and it is a pain trying to find one specific card/dowel once you have a whole chest full of them.

The walkthrough is a great idea.

Sharing codes would be nice. I'm totally fine with codes being something you can look up on the wiki, honestly.

100% agree about crafting Sburb disks, but I would probably just make an adventure map where the disks already exist somewhere (and disable the crafting recipe) rather than go searching for a frog temple in an otherwise vanilla overworld.

Dream selves, death beds, kissing, and god tiers would all be nice,

Dead sessions for single players would be fine as long as there was a config option to turn it off, and some way to Scratch out of it.

4th walls to hop between servers could make for some awesome moments, though I think the server owners just using Qcraft for this would work fine, right?

> The ability to play as a Troll with an Alternia world setting for the overworld

This sounds like an entirely new mod. Creating a whole new overworld with as much depth and content as the original one is a massive undertaking. I like the trolls, but remember that a normal Sburb session wouldn't involve them at all because Jack Noir is not a normal occurence.

>A config that disables the in-game chat and requires players to use Pesterchum (Also, implement Pesterchum!)

I get what you're going for here, but chat kind of already is Pesterchum. Everyone has screennames, you can message groups or whisper to individuals, and there's a log of previous messages. So I don't see it as that important to replace the current chat system.

>A config that disables the in-game inventory and requires players to use their Sylladex

This would be amusing (if a little frustrating for new players, potentially) but I think the Sylladex would have to be reworked for this to work, right? Don't you currently need to have an item in your inventory before you can Captchalogue it?

>Clothing that covers the player's skin but can be worn under armor

I think there are other mods for this

>A First Guardian somewhere on the MineCraft overworld

Really cool idea, but I have no idea how that would work. How does an omnipotent animal behave in minecraft? Who do they protect, if anyone? What do they actually do to gameplay?

>A config that enables the Reckoning to destroy the overworld if players don't enter the game within a certain time limit of getting the Sburb disks

Definitely would like this.

**Comment by kirderf1** [comment]
Github issues are not appropriate for this kind of feature-suggestion-batch. Until A later date, I'll leave this issue open as a reference.
It's more ideal to bring suggestion batches like this up in our discord instead.
