### ISSUE TITLE
typo in mob ai?

### ISSUE THREAD

**Issue by Jkosio23** [mraof/Minestuck#470]
https://github.com/mraof/Minestuck/blob/fd80e52a3abc490bd3fed8012cb0e3437a73b88b/src/main/java/com/mraof/minestuck/entity/ai/attack/AttackByDistanceGoal.java#L147 Says Mth. instead of Math. ?

**Comment by Jkosio23** [comment]
line 155 also says Mth, idk if it was a typo or not, i'm just looking through the code for the imp ai that stops aggro at the certain echeladder tier

**Comment by kirderf1** [comment]
That's not a typo, it refers to minecrafts class `Mth`. Likely named as such as it serves a similar purpose to javas `Math` class, but where they overlap, `Mth` is sacrificing accuracy for performance.
Had it been an actual typo so that it didn't match any class or the wrong class, the code wouldn't compile in the first place.
