### ISSUE TITLE
Entry command

### ISSUE THREAD

**Issue by kirderf1** [mraof/Minestuck#486]
A command for triggering entry could be mildly interesting, and is something I've been thinking about before, primarily as a tool to streamline testing just a little bit.

Running the command with no arguments should trigger entry for the player executing the command and at their position. It could then be interesting with an optional argument for which player that the entry will be for, as well as an optional argument for the center position of the entry area.

I'm writing this issue mostly to get the thought out of my head, but I'd also like to see if there's any interest or use case for such a feature outside of dev testing, since that matters when deciding if it's worth adding. Reply if you've got a thought or opinion to add!

**Comment by metalmint** [comment]
Oh yeah this would actually be very useful for a specific modpack of mine! Since there's a thing going on with it where layers have to stand in the perfect spot while eating the cruxite artifact to make sure they experience a clean enter.

I was going to just tell them where exactly to stand or teleport them to the right spot just before the eat the artifact, and then teleporting them back right after, but you can see how that could cause issues.

**Comment by InfectedGriffon** [comment]
doesn't seem that hard to implement? I think I have enough experience with hacked-together commands to make this work

**Comment by kirderf1** [comment]
Yeah, should be good enough of a reason for adding that command then.

Also, I strongly recommend making sure that the command doesn't trigger the title selection screen in order to avoid some headaches with the implementation.

@InfectedGriffon would you like to give it a try?
