### ISSUE TITLE
Fatal crash with Cauldron

### ISSUE THREAD

**Issue by Sunconure11** [mraof/Minestuck#78]
I know Cauldron is no longer supported, but, I am currently using it at the moment to increase TPS until I can find a better way to do so, and I get this crash when I attempt to hook up with another player on the computer:

http://pastebin.com/hn43pdry

**Comment by kirderf1** [comment]
Looks like Cauldron have removed the downloads. Probably best to wait for it to be back up before trying to do anything about it, I guess.

**Comment by Sunconure11** [comment]
I found a mirror.

http://tcpr.ca/

**Comment by kirderf1** [comment]
Ah, okay. I'll see if I can resolve this problem now then.

**Comment by kirderf1** [comment]
Can't think of how to resolve this issue as it is right now, but I'll leave the issue open for now.

**Comment by Sunconure11** [comment]
Hm, a new version of Cauldron was released to the mirror. Maybe you can try and figure it out now?

**Comment by Sunconure11** [comment]
The entire Git was released to that mirror.

**Comment by kirderf1** [comment]
Hmm, really? That would mean that I can check out the source code for it. Where on the mirror is it?

**Comment by Sunconure11** [comment]
http://tcpr.ca/cauldron Under here

**Comment by Sunconure11** [comment]
You will see the download for the Cauldron Git.

**Comment by kirderf1** [comment]
Sorry for the long delay. I have created a potential fix in version 129. Tell me if it works or not.

**Comment by Sunconure11** [comment]
I will test it when I update my server later on.

**Comment by Sunconure11** [comment]
It works, but, we are having a hard time placing stuff in edit mode.

**Comment by Sunconure11** [comment]
The server player cannot place down blocks at all.

**Comment by kirderf1** [comment]
Okay. I'll see if I can find what may cause it.

**Comment by kirderf1** [comment]
So, I take it that it applies to all blocks, and that they are only placed on the client side, thus causing the block to be placed only to vanish shortly after being placed?

**Comment by Sunconure11** [comment]
Yes.

**Comment by kirderf1** [comment]
Okay, I think I finally found the problem to it, and I'd say that it's more of a fault on cauldron's side than anything. The problem lies in a part of the forge-bukkit integration, that can be bypassed by doing a thing with a bukkit event. I haven't had any experience with bukkit myself, so I don't know how to create a plugin for fixing it. But I do know that it can be fixed by setting the use item in hand to the "Allow" result. (And only do that when the result is at "Default" for better compability with any other plugins using that event)
